version: '3.9'

services:
  app:
    container_name: app
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/app
      - node_modules:/usr/src/app/node_modules
    ports:
      - ${PORT}:${PORT}
    env_file:
      - .env
    depends_on:
      - postgres-db

  postgres:
    container_name: postgres
    restart: unless-stopped
    build:
      context: ./postgres
      dockerfile: Dockerfile
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      PG_DATA: /var/lib/postgresql/data
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - data:/var/lib/postgresql/data

networks:
  default:
    driver: bridge

volumes:
  node_modules:
  data:
