version: '3.9'

services:
  main:
    container_name: main
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/app
      - node_modules:/usr/src/app/node_modules
    ports:
      - ${PORT}:${PORT}
    command: npm run start:dev
    env_file:
      - .env    
    depends_on:
      - postgres

  postgres:
    container_name: postgres
    image: postgres:latest    
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      PG_DATA: /var/lib/postgresql/data
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - data:/var/lib/postgresql/data
networks:
  main:
    name: main
    driver: bridge
  postgres:
    name: postgres
    driver: bridge
volumes:
  app:
  node_modules:
  data:
